################################# Default configuration ###################
baseURL = "https://www.labossadurina.com/"
title = "La Bossa d'Urina"
theme = "meghna-hugo"
# post pagination
paginate = "6"
# post excerpt
summaryLength = "15"
disqusShortname = "" # get your shortname form here : https://disqus.com
disableLanguages = ["en"]
defaultContentLanguage = "ca"

############################# Plugins ##########################
# css plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/font-awesome/css/all.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

# js plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lozad.min.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

################### English Navigation ########################
[[Languages.en.menu.main]]
name = "Notícies"
url = "#blog"
weight = 1

[[Languages.en.menu.main]]
name = "Discografia"
url = "#discography"
weight = 2

[[Languages.en.menu.main]]
name = "World Tour"
url = "#tour"
weight = 3

[[Languages.en.menu.main]]
name = "Bio"
url = "#bio"
weight = 4

[[Languages.en.menu.main]]
name = "Vídeos"
url = "#videos"
weight = 5



################### Catalan Navigation ########################
[[Languages.ca.menu.main]]
name = "Notícies"
url = "#blog"
weight = 1

[[Languages.ca.menu.main]]
name = "Discografia"
url = "#discography"
weight = 2

[[Languages.ca.menu.main]]
name = "World Tour"
url = "#tour"
weight = 3

[[Languages.ca.menu.main]]
name = "Bio"
url = "#bio"
weight = 4

[[Languages.ca.menu.main]]
name = "Vídeos"
url = "#videos"
weight = 5


############################# Default Parameters ##########################
[params]
logo = "images/logo.png"
# Meta data
description = "Nihilistic, Sexual, and Transatlantic Music"
author = "La Bossa d'Urina"
# Google Analytics
google_analytics_id = "" # Your ID
# post share
post_share = true

# preloader
[params.preloader]
enable = false
preloader = "images/logo.png"

# cookies
[params.cookies]
enable = false
expire_days = 2

# google map
[params.map]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "41.6062"
map_longitude = "2.2871"
map_marker = "images/marker.png"

############################# social icons ##########################
[[params.social]]
icon = "fab fa-spotify" # themify icon pack : https://themify.me/themify-icons
link = "https://open.spotify.com/artist/71wwC1YTioY5niuzCoNPbY?si=MJ1_G8mER-SNhU5vtYWfCA&dl_branch=1"

[[params.social]]
icon = "fab fa-bandcamp" # themify icon pack : https://themify.me/themify-icons
link = "https://labossadurina.bandcamp.com/releases"

[[params.social]]
icon = "fab fa-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/labossadurina/"

[[params.social]]
icon = "fab fa-mastodon" # themify icon pack : https://themify.me/themify-icons
link = "https://universeodon.com/@labossadurina"

[[params.social]]
icon = "fab fa-twitter" # themify icon pack : https://themify.me/themify-icons
link = "https://twitter.com/LaBossadUrina"

[[params.social]]
icon = "fab fa-facebook" # themify icon pack : https://themify.me/themify-icons
link = "http://facebook.com/labossadurina"

[[params.social]]
icon = "fab fa-youtube" # themify icon pack : https://themify.me/themify-icons
link = "https://www.youtube.com/channel/UCWYUoGNsmmwi9eEhylrZaXQ"


################################ English Language ########################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 3
home = "Home"
copyright = "Copyright &copy; {{ now.Year }} Designed by [Themefisher](https://themefisher.com) & Developed by [Gethugothemes](https://gethugothemes.com)"

################################ Catalan Language ########################
[Languages.ca]
languageName = "Ca"
languageCode = "ca"
contentDir = "content/catalan"
weight = 1
home = "Home"
copyright = "Copyright &copy; 2011-{year} Designed by [Themefisher](https://themefisher.com) & [Uri Nieto](https://www.urinieto.com); Developed by [Gethugothemes](https://gethugothemes.com) & [Uri Nieto](https://www.urinieto.com)"
